karisma/api/urls.py
from django.urls import path

from .views import *

app_name = 'api'

urlpatterns = [
    path('take-presence', TakePresenceEndPoint.as_view(), name='take-presence'),
    path('login', LoginEndPoint.as_view(), name='login'),
    path('logout', LogoutEndPoint.as_view(), name='logout'),
    path('auth-user', AuthenticatedUser.as_view(), name='auth-user'),
]

karisma/assistant/urls.py
from .views import *
from django.urls import path

app_name = 'assist'

urlpatterns = [
    path('', AssistantLanding.as_view(), name='landing'),
    path('create-class', CreateClass.as_view(), name='create-class'),
    path('join-class', JoinAssistantClas.as_view(), name='join-class'),
    path('change-username', AssistantChangeUsername.as_view(), name='change-username'),
    path('change-password', AssistantChangePassword.as_view(), name='change-password'),
    path('generate-token', GenerateTokenToResetPassword.as_view(), name='generate-token'),
    path('finder', FinderView.as_view(), name='finder'),
    path('download-today', DownloadTodayPresent.as_view(), name='today-present'),
    path('upload-boarding-hosue', CreateBoardingHouse.as_view(), name='create-boarding'),
    path('boarding-hosue-list', BoardingHouseList.as_view(), name='boarding-list'),

    path('my-class', MyClassList.as_view(), name='my-class-list'),
    path('my-class/<slug:link>/generate-qr', GenerateQRCodeView.as_view(), name='generate-qr'),
    path('my-class/<slug:link>/file/delete/<int:item_pk>', DeleteFile.as_view(), name='delete-file'),
    path('my-class/<slug:link>/file/<name>', QRCodeView.as_view(), name='view-qr'),
    path('my-class/<slug:link>/file', SeeAllFiles.as_view(), name='file-class'),
    path('my-class/<slug:link>/recaps/<qr_code>/export', recaps_csv, name='export'),
    path('my-class/<slug:link>/recaps/<qr_code>/absence', SetStudentAbsence.as_view(), name='absence'),
    path('my-class/<slug:link>/recaps/<qr_code>', PresenceRecap.as_view(), name='recaps'),
    path('my-class/<slug:link>/recaps', QRGeneratedList.as_view(), name='generated-qr'),
    path('my-class/<slug:link>/update-detail', update_class_detail, name='update-detail'),
    path('my-class/<slug:link>/score/update', UpdateScore.as_view(), name='update-score'),
    path('my-class/<slug:link>/score', AddStudentScore.as_view(), name='score'),
    path('my-class/<slug:link>/score/view', ViewStudentScore.as_view(), name='view-score'),
    path('my-class/<slug:link>/score/view/export', DownloadScore.as_view(), name='download-score'),
    path('my-class/<slug:link>/students', SeeAllStudents.as_view(), name='see-all-students'),
    path('my-class/<slug:link>', MyClass.as_view(), name='my-class'),
]

karisma/labs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('static/<path>', serve, settings.STATIC_ROOT),
    path('media/<path>', serve, settings.MEDIA_ROOT),
]

urlpatterns += [
    path('file/', include('file_control.urls', namespace='file')),
    path('assistant/', include('assistant.urls', namespace='assist')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('presence.urls', namespace='presence')),
]

if not settings.DEBUG or settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

karisma/assistant/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from presence.models import ClassName


class TokenToResetPassword(models.Model):
    token = models.SlugField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    valid_until = models.DateTimeField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        now = timezone.now()
        return f"{self.token} is {'expired' if now > self.valid_until else 'available'}"

    def val_stamp(self):
        return self.valid_until.strftime('%a %H:%M  %d/%m/%y')


class StudentScore(models.Model):
    name = models.CharField(max_length=255)
    score = models.FloatField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='score', related_query_name='score')
    classification = models.CharField(max_length=255)
    class_name = models.ForeignKey(ClassName, on_delete=models.CASCADE, related_name='user_score',
                                   related_query_name='user_score')

    def __str__(self):
        return f"{self.user.username} - {self.name} : {self.score}"


class ResetPasswordRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_done = models.BooleanField(default=False)
    token = models.ForeignKey(TokenToResetPassword, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} is requested" if not self.is_done else f"{self.user} has changed password"

karisma/assistant/forms.py
from django.apps import apps
from django.forms import ModelForm, DateTimeInput
from django.contrib.auth.models import User
from django import forms

Files = apps.get_model('file_control', 'Files')
Recap = apps.get_model('presence', 'Recap')
ClassName = apps.get_model('presence', 'ClassName')
GenerateQRCode = apps.get_model('presence', 'GenerateQRCode')
UserData = apps.get_model('presence', 'UserData')
BoardingHouse = apps.get_model('presence', 'BoardingHouse')


class ClassCreationForms(ModelForm):
    class Meta:
        model = ClassName
        fields = '__all__'


class GenerateQRCodeForms(ModelForm):
    class Meta:
        model = GenerateQRCode
        fields = ['valid_until']

        widgets = {
            'valid_until': DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'})
        }


class UserChangeDataForms(ModelForm):
    class Meta:
        model = User
        fields = ['username']


class CreateClassForms(ModelForm):
    class Meta:
        model = ClassName
        fields = ["name"]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }


class BoardingHouseForms(ModelForm):
    class Meta:
        model = BoardingHouse
        fields = ['name', 'spec', 'link']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'spec': forms.TextInput(attrs={'class': 'form-control w-100'}),
            'link': forms.TextInput(attrs={'class': 'form-control'}),
        }

karisma/assistant/views.py
import csv
import datetime
import os
from itertools import chain

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.views import PasswordChangeView
from django.db.models import Q as __
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import *
from django.core.mail import send_mail

from .forms import *
from .models import *
from .utils import *

pre_test = [f"Pre-test {x}" for x in range(17)]
lap = [f"Laporan {x}" for x in range(17)]
classification = ['PRETEST', 'LAPORAN', 'POST-TEST', 'UTS', 'UAS']


def templates(temp: str):
    return "temp_/{}.html".format(temp)


class AssistantLanding(TemplateView):
    template_name = templates('landing')

    def get_context_data(self, *args, **kwargs):
        context = super(AssistantLanding, self).get_context_data(*args, **kwargs)
        a = list(range(20))
        class_ = ClassName.objects.all().count()
        student = UserData.objects.all().exclude(__(user__username__contains='admin'))
        context['loop'] = a
        context['class'] = class_
        context['student'] = student
        return context

    @method_decorator(login_required(login_url=settings.LOGIN_URL))
    @method_decorator(
        user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        return super(AssistantLanding, self).dispatch(request, *args, **kwargs)


class SeeAllFiles(ListView):
    model = Files
    context_object_name = 'files'
    template_name = templates('list_')

    def get_queryset(self):
        get_date = self.request.GET.get('date')
        model = self.model
        return model.objects.filter(class_name__link=self.kwargs['link']).filter(
            __(time_stamp__date=get_date)) if get_date else model.objects.filter(class_name__link=self.kwargs['link'])

    def get_context_data(self, **kwargs):
        context = super(SeeAllFiles, self).get_context_data(**kwargs)
        class_ = ClassName.objects.get(link=self.kwargs['link'])

        context['class'] = class_
        return context

    @method_decorator(login_required(login_url=settings.LOGIN_URL))
    @method_decorator(
        user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        return super(SeeAllFiles, self).dispatch(request, *args, **kwargs)


class SeeAllStudents(ListView):
    model = ClassName
    template_name = templates('student_list')
    context_object_name = 'students'

    def get_queryset(self):
        return self.model.objects.get(link=self.kwargs['link']).students.all()


class DeleteFile(View):
    def get(self, *args, **kwargs):
        raise Http404()

    def post(self, *args, **kwargs):
        item = Files.objects.get(pk=kwargs['item_pk'])
        messages.info(self.request, f"Item {item} has been deleted")
        item.delete()

        return redirect(reverse('assist:file-class', kwargs={'link': kwargs['link']}))

    @method_decorator(login_required(login_url=settings.LOGIN_URL))
    @method_decorator(
        user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False)))
    def dispatch(self, request, *args, **kwargs):
        return super(DeleteFile, self).dispatch(request, *args, **kwargs)


@login_required(login_url=settings.LOGIN_URL)
@method_decorator(
    user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/'))
def download_file(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fp:
            response = HttpResponse(fp.read(), content_type='application/file')
            response['Content-Disposition'] = f"inline; filename={os.path.basename(file_path)}"
            return response
    raise Http404


class QRGeneratedList(ListView):
    model = GenerateQRCode
    template_name = templates('qr_list')
    context_object_name = 'qrcodes'

    def get_queryset(self):
        model = self.model
        class_name = ClassName.objects.get(link=self.kwargs['link'])
        query = model.objects.filter(class_name=class_name).order_by('-pk')
        return query

    @method_decorator(login_required(login_url=settings.LOGIN_URL))
    @method_decorator(
        user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        return super(QRGeneratedList, self).dispatch(request, *args, **kwargs)


class PresenceRecap(ListView):
    template_name = templates('recaps')
    model = Recap
    context_object_name = 'recaps'

    def get_queryset(self):
        """ my class only """
        model = self.model
        get_code = GenerateQRCode.objects.get(qr_code=self.kwargs['qr_code'])
        return model.objects.filter(qr=get_code)

    @method_decorator(login_required(login_url=settings.LOGIN_URL))
    @method_decorator(
        user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        return super(PresenceRecap, self).dispatch(request, *args, **kwargs)


class QRCodeView(View):
    def get(self, *args, **kwargs):
        file = GenerateQRCode.objects.filter(qr_img=f"qr/{self.kwargs['name']}")
        if not file:
            messages.warning(self.request, 'file not found')
            return redirect(reverse('assist:generated-qr', kwargs={'link': self.kwargs['link']}))
        img = open(os.path.join(settings.MEDIA_ROOT, file[0].qr_img.name), 'rb').read()
        return HttpResponse(img, content_type='image/png')

    @method_decorator(login_required(login_url=settings.LOGIN_URL))
    @method_decorator(
        user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        return super(QRCodeView, self).dispatch(request, *args, **kwargs)


#
# class CreateClass(CreateView):
#     template_name = 'temp_/create.html'
#     form_class = ClassCreationForms
#     model = ClassName
#
#     def form_valid(self, form):
#         return super(CreateClass, self).form_valid(form)
#
#     def get_context_data(self, **kwargs):
#         context = super(CreateClass, self).get_context_data(**kwargs)
#         context['class_list'] = class_list
#
#         return context

class MyClassList(ListView):
    model = ClassName
    template_name = templates('class_list')
    context_object_name = 'classes'

    def get_queryset(self):
        model = self.model
        return model.objects.filter(__(pr=self.request.user) | __(creator=self.request.user)).distinct()

    @method_decorator(login_required(login_url=settings.LOGIN_URL))
    @method_decorator(
        user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        return super(MyClassList, self).dispatch(request, *args, **kwargs)


class MyClass(DetailView):
    model = ClassName
    template_name = templates('my_class')
    slug_field = 'link'
    slug_url_kwarg = 'link'
    context_object_name = 'class'

    def get_context_data(self, **kwargs):
        context = super(MyClass, self).get_context_data(**kwargs)
        qr_active = GenerateQRCode.objects.filter(class_name__link=self.kwargs['link'])
        form = CreateClassForms()

        context['class_list'] = class_list
        context['course_list'] = course_list
        context['links'] = qr_active if qr_active.exists() else None
        context['form'] = form
        return context

    @method_decorator(login_required(login_url=settings.LOGIN_URL))
    @method_decorator(
        user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        try:
            return super(MyClass, self).dispatch(request, *args, **kwargs)
        except Http404:
            return redirect('assist:my-class-list')


class CreateClass(CreateView):
    form_class = CreateClassForms
    template_name = templates('create')
    success_url = reverse_lazy('assist:my-class-list')

    def form_valid(self, form):
        # gen = self.request.POST.get('gen')
        gen = form.cleaned_data.get('name')
        name, link = set_class_name(gen)
        code = slug_generator(10)

        code_list = [c.unique_code for c in ClassName.objects.all()]
        code = check_slug(code, code_list, 10)

        find = ClassName.objects.filter(link=link)
        if find:
            link = f"{link}-{code}"

        form.instance.name = name
        form.instance.link = link
        form.instance.unique_code = code
        form.instance.creator = self.request.user
        return super(CreateClass, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateClass, self).get_context_data(**kwargs)

        context['class_list'] = class_list
        context['course_list'] = course_list
        return context

    # @method_decorator(login_required(login_url=settings.LOGIN_URL))
    # @method_decorator(
    #     user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/'))
    # def dispatch(self, request, *args, **kwargs):
    #     return super(CreateClass, self).dispatch(request, *args, **kwargs)


@login_required(login_url=settings.LOGIN_URL)
@user_passes_test(lambda u: u.is_staff and (u.user.is_controller if hasattr(u, 'user') else False), '/')
def update_class_detail(request, link):

karisma/assistant/templates/temp_/backup.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5 mx-auto">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <button class="btn btn-primary">Backup</button>
        </div>
    </form>
</div>
{% endblock %}

karisma/assistant/templates/temp_/finder.html
{% extends 'base.html' %}

{% block title %} Finder {% endblock %}

{% block content %}
<div class="container mt-5">
    <a class="btn btn-secondary mb-3" href="{% url 'assist:landing' %}">Back to Assistant</a>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="data">Find by Username atau NIM Mahasiswa</label>
                    <input type="text" name="data" id="data" class="form-control">
                </div>
                <div class="form-group">
                    <button class="btn btn-primary">Find</button>
                </div>
            </form>
        </div>
    </div>
    {% if result %}
    <div class="card mt-5">
        <div class="card">
            <div class="card-body">
                {% for user in result %}
                {{ user }} - {% if nim %} {{ user.nim }} {% else %} {{ user.user.nim }} {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

karisma/assistant/templates/temp_/join_class.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5 mx-auto">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="class_code">Kode Pleton</label>
            <input type="text" name="class_code" id="class_code" class="form-control">
        </div>
        <div class="form-group">
            <button class="btn btn-primary">Save</button>
            <a href="{% url 'assist:my-class-list' %}" class="btn btn-secondary">Pleton Saya</a>
            <a href="{% url 'assist:landing' %}" class="btn btn-secondary">Back To Home</a>
        </div>
    </form>
</div>
{% endblock %}

karisma/assistant/templates/temp_/landing.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid my-5">
    <div class="row mx-auto align-items-center justify-content-center">
        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Pleton Saya</h5>
                    <h6 class="card-subtitle">Seluruh Pleton yang Saya Buat / Sebagai asisten</h6>
                    <p class="card-text">{{ class }} Pleton</p>
                    <a href="{% url 'assist:my-class-list' %}" class="btn btn-primary col">Lihat Pleton</a>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Total Mahasiswa</h5>
                    <h6 class="card-subtitle">Seluruh mahasiswa yang sudah terdaftar</h6>
                    <p class="card-text">{{ student.count }} Mahasiswa </p>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Buat Pleton</h5>
                    <p class="card-text">Buat Pleton baru</p>
                    <a href="{% url 'assist:create-class' %}" class="btn btn-primary col">Buat Pleton</a>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Join Panitia Pleton</h5>
                    <p class="card-text">Masuk Sebagai panitia Pleton agar kamu dapat privilege khusus</p>
                    <a href="{% url 'assist:join-class' %}" class="btn btn-primary col">Join Pleton</a>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Ubah Username</h5>
                    <a href="{% url 'assist:change-username' %}" class="btn btn-primary col">Proses</a>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Generate Token untuk Ubah password</h5>
                    <a href="{% url 'assist:generate-token' %}" class="btn btn-primary col">Proses</a>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Finder</h5>
                    <p class="card-text">Finder ini berguna untuk mencari data mahasiswa yang terdata di sistem, cari berdasarkan username atau menggunakan nim mahasiswa tersebut</p>
                    <a href="{% url 'assist:finder' %}" class="btn btn-primary col">Proses</a>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Download Today's Present</h5>
                    <p class="card-text">Fitur ini digunakan untuk mengunduh seluruh data presensi yang ada</p>
                    <a href="{% url 'assist:today-present' %}" class="btn btn-primary col">Proses</a>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Pendataan Kost Terdekat</h5>
                    <p class="card-text">Fitur ini digunakan untuk mendata kost terdekat dari kampus ITPLN</p>
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'assist:create-boarding' %}" class="btn btn-primary col">Data Sekarang</a>
                        </div>
                        <div class="col">
                            <a href="{% url 'assist:boarding-list' %}" class="btn btn-primary col">Data Kost</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

karisma/assistant/templates/temp_/my_class.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5 mx-auto">
    <div class="form-group row">
        <div class="col-lg-3 col-sm-3">Nama Pleton</div>
        <div class="col-lg-9 col-sm-9">
            <input type="text" name="name" id="name" value="{{ class.name }}" class="form-control bg-transparent" readonly >
        </div>
    </div>
    <div class="form-group row">
        <div class="col-lg-3 col-sm-3">Kode Pleton</div>
        <div class="col-lg-9 col-sm-9">
            <input type="text" name="code" id="code" class="form-control bg-transparent" value="{{ class.unique_code }}" readonly>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-lg-3 col-sm-3">Penanggung Jawab Mentorship</div>
        <div class="col-lg-9 col-sm-9">
            <input type="text" name="pj" id="pj" class="form-control bg-transparent" value="{{ class.creator }}" readonly>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-lg-3 col-sm-3">Mentorship Pleton</div>
        <div class="col-lg-9 col-sm-9">
            <select name="assist" id="assist" class="custom-select" multiple>
                {% if class.pr.all %}
                {% for pr in class.pr.all %}
                <option>{{ pr }}</option>
                {% endfor %}
                {% else %}
                <option>No Mentorship Registered Here yet</option>
                {% endif %}
            </select>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-12 col-md-3 col-lg-3">Langsung Generate QRCode</div>
        <div class="col-12 col-md-9 col-lg-9">
            <a type="button" class="btn btn-primary col" href="{% url 'assist:generate-qr' view.kwargs.link %}">
                Generate QR Code
            </a>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-12 col-md-3 col-lg-3">Lihat Rekap Presensi</div>
        <div class="col-12 col-md-9 col-lg-9">
            <a href="{% url 'assist:generated-qr' view.kwargs.link %}" class="btn btn-primary col"> Lihat Recap</a>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-3 col-sm-3">Ubah Detail Pleton</div>
        <div class="col-12 col-md-9 col-lg-9">
            <button type="button" class="btn btn-primary col" data-toggle="modal"
                    data-target="#staticBackdropUpdate">Ubah Detail Pleton
            </button>
        </div>
    </div>
</div>

<!-- MODAL SECTION -->
{% include 'temp_/modal/modal_update.html' %}
{% include 'temp_/modal/modal_generate_confirm.html' %}
{% endblock %}

karisma/assistant/templates/temp_/qr_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <a href="{% url 'assist:generate-qr' view.kwargs.link %}" class="btn btn-primary mb-3">Generate QR</a>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">code</th>
                <th scope="col">Recaps</th>
                <th scope="col">created</th>
                <th scope="col">creator</th>
                <th scope="col">validate</th>
            </tr>
        </thead>
        <tbody>
        {% for code in qrcodes %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'assist:view-qr' view.kwargs.link code.qr_name %}">{{ code.qr_code }}</a></td>
                <td><a href="{% url 'assist:recaps' view.kwargs.link code.qr_code %}" class="btn btn-primary">See</a></td>
                <td>{{ code.created }}</td>
                <td>{{ code.creator }}</td>
                <td>{{ code.valid_until }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

karisma/assistant/templates/temp_/score.html
{% extends 'base.html' %}

{% block title %} Mahasiswa {{ class_name }} {% endblock %}

{% block content %}
<div class="container mt-5">
    <form method="get">
        <div class="form-group">
            <label for="classification">Jenis Rekap</label>
            <select name="classification" id="classification" class="form-control">
                <option selected value="">. . .</option>
                {% for class in classification %}
                <option value="{{ forloop.counter }}">{{ class }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <button class="btn btn-primary">Set</button>
            <a href="{% url 'assist:view-score' class.link %}" class="btn btn-outline-primary">Download Nilai</a>
        </div>
    </form>

    {% if show %}
    <div class="card">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if multiple %}
                <div class="form-group">
                    <label for="named">Urutan ke </label>
                    <select name="named" id="named" class="form-control" required>
                        <option selected value="">. . .</option>
                        {% for item in items %}
                        <option value="{{ item }}">{{ item }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% else %}
                <input type="text" name="named" id="named" readonly value="{{ name }}" hidden>
                {% endif %}
                {% for std in class_name.students.all %}
                <div class="form-group row">
                    <div class="col-lg-3">
                        <input type="text" name="data{{ forloop.counter }}" id="data{{ forloop.counter }}"
                               class="form-control" value="{{ std.user.nim }}" readonly>
                    </div>
                    <div class="col-lg-9">
                        <input type="number" name="score{{ forloop.counter }}" id="{{ forloop.counter }}"
                               class="form-control" max="100" title="nilai maximum adalah 100" required>
                    </div>
                </div>
                {% endfor %}
                <div class="form-group">
                    <button class="btn btn-primary">Save</button>
                </div>
            </form>

        </div>
    </div>
    {% endif %}
</div>
{% endblock %}