karisma/api/urls.py
from django.urls import path

from .views import *

app_name = 'api'

urlpatterns = [
    path('take-presence', TakePresenceEndPoint.as_view(), name='take-presence'),
    path('login', LoginEndPoint.as_view(), name='login'),
    path('logout', LogoutEndPoint.as_view(), name='logout'),
    path('auth-user', AuthenticatedUser.as_view(), name='auth-user'),
]

karisma/labs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('static/<path>', serve, settings.STATIC_ROOT),
    path('media/<path>', serve, settings.MEDIA_ROOT),
]

urlpatterns += [
    path('file/', include('file_control.urls', namespace='file')),
    path('assistant/', include('assistant.urls', namespace='assist')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('presence.urls', namespace='presence')),
]

if not settings.DEBUG or settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

karisma/presence/urls.py
from .views import *
from django.urls import path

app_name = 'presence'


urlpatterns = [
    path('join-class', JoinClass.as_view(), name='join-class'),
    path('data-completions', DataComplement.as_view(), name='complete-data'),
    path('reset-password/request', RequestPasswordReset.as_view(), name='request-password-reset'),
    path('reset-password/<token>', ResetPassword.as_view(), name='reset-password'),
    path('presence', Presence.as_view(), name='take-presence'),
    path('class', ClassList.as_view(), name='class-list'),
    path('class/<slug:link>/upload-file', UploadFileByClass.as_view(), name='upload-file'),
    path('class/<slug:link>/file-list', FileListClass.as_view(), name='file-list-class'),
    path('class/<slug:link>/recaps', MyPresenceRecaps.as_view(), name='my-presence-recap'),
    path('class/<slug:link>/recaps/score', SeeMyScoreView.as_view(), name='my-score-recap'),
    path('dashboard', LandingView.as_view(), name='landing'),

    path('about', about_us, name='about'),
    path('merch', merchandise, name='merchandise'),
    path('faq', faq, name='faq'),

    path('', landing, name='landing-no-login'),
]

karisma/templates/_base.html
<!doctype html>

{% load static %}
{% load l10n %}
{% load i18n %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Untree.co">
    <link rel="shortcut icon" href="{% static 'user/landing/images/icon.png' %}">

    <meta name="description" content=""/>
    <meta name="keywords" content="bootstrap, bootstrap4"/>

    <!-- Bootstrap CSS -->
    <link href="{% static 'user/landing/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="{% static 'user/landing/css/tiny-slider.css' %}" rel="stylesheet">
    <!-- google analytic -->
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-C9658TXYYW"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'G-C9658TXYYW');
    </script>
    <title>{% block title %}{% endblock %}KARISMA</title>
    {% block head %}
    {% endblock %}
</head>

<body>

<!-- Start Header/Navigation -->
<nav class="custom-navbar navbar navbar-expand-md navbar-dark bg-transparent position-relative w-100"
     arial-label="Furni navigation bar" style="z-index: 1">

    <div class="container">
        <a class="navbar-brand" href="/"><img alt=""
                                                       src="{% static 'user/landing/images/icon-removebg-preview.png' %}"
                                                       alt=""
                                                       width="60"></a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni"
                aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsFurni">
            <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0 fs-6">
                <li class="nav-item {% if path == '/' %}  active{% endif %}">
                    <a class="nav-link text-lowercase" href="/">Home</a>
                </li>
                <li class="nav-item {% if path == '/about' %}  active{% endif %}">
                    <a class="nav-link " href="{% url 'presence:about' %}">About us</a>
                </li>
                <li class="nav-item {% if path == '/merch' %}  active{% endif %}">
                    <a class="nav-link" href="{% url 'presence:merchandise' %}">Merchandise</a>
                </li>
                <li>
                    <a class="nav-link"
                       href="https://mamikos.com/cari/stt-pln-stt-pln-duri-kosambi-kota-jakarta-barat-daerah-khusus-ibukota-jakarta-indonesia/all/bulanan/0-15000000?rent=2&sort=price,-&price=10000-20000000&singgahsini=0">Info
                        Kost</a>
                </li>
                <li class="nav-item {% if path == '/faq' %}  active{% endif %}">
                    <a class="nav-link " href="{% url 'presence:faq' %}">FAQ</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'presence:landing' %}">Dashboard</a>
                </li>
            </ul>
        </div>
    </div>

</nav>


{% block content %}
{% endblock %}

<section class="">

    <!-- Footer -->
    <footer class="text-center text-white" style="background-color:rgb(221,200,183)">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: CTA -->
            <section class="">
                <p class="d-flex justify-content-center align-items-center text-dark">
                    <span class="me-3">Register for free</span>
                    <a type="button" href="/accounts/signup/" class="btn btn-outline-light btn-rounded">
                        Sign up!
                    </a>
                </p>
            </section>
            <!-- Section: CTA -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3 text-dark" style="background-color: rgb(221,200,183)">
            © 2023 Copyright:
            <a class="text-dark text-decoration-none" href="">KARISMA RENAISANS</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
</section>


<script src="{% static 'user/landing/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'user/landing/js/tiny-slider.js' %}"></script>
<script src="{% static 'user/landing/js/custom.js' %}"></script>
</body>

</html>

karisma/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="{% static 'user/images/karisma.png' %}" rel="shortcut icon" />
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
              integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-C9658TXYYW"></script>
        <script>
            window.dataLayer = window.dataLayer || [];

            function gtag() {
                dataLayer.push(arguments);
            }

            gtag('js', new Date());

            gtag('config', 'G-C9658TXYYW');
        </script>

        <title>{% block title %}{% endblock %}</title>
        {% block head %}
        {% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light position-sticky">
        <div class="container-fluid ">
            <div >
                <img
                src="{% static 'user/images/karisma.png' %}"
                width="50"
                height="50"
                class="d-inline-block align-top mr-2"
                alt="Logo Karisma"
                /> <a class="navbar-brand mt-1" href="/dashboard">Renaisans 2023</a>
            </div>

            <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
            ><span class="navbar-toggler-icon"></span></button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mt-1">
                    <li class="nav-item"><a class="nav-link" href="{% url 'presence:landing' %}">Home</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href="/accounts/logout/" class="nav-link">Logout</a></li>
                    {% else %}
                    <li><a href="/accounts/login/" class="nav-link">Login</a></li>
                    <li><a href="/accounts/signup/" class="nav-link">Register</a></li>
                    {% endif %}
                    {% if request.user.user.is_controller %}
                    <a href="{% url 'assist:landing' %}" class="nav-link bold">Committee Page</a>
                    {% endif %}
                </ul>
            </div>
        </div>



    </nav>
    {% if request.user.is_authenticated %}
        <div class="container mt-5">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Account Info</h5>
                    <div class="row mx-auto">
                        <div class="col-lg-3 col-sm-3">Username</div>
                        <div class="col-lg-9 col-sm-9">
                            <input type="text" name="my-account" id="my-account" class="form-control" value="{{ request.user.username }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
        {% if messages %}
            {% for msg in messages %}
        <div class="container mt-5 mx-auto">
            <div class="alert alert-{{ msg.tags }}"> {{ msg }} </div>
        </div>

            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
    </body>
</html>