karisma/api/urls.py
from django.urls import path

from .views import *

app_name = 'api'

urlpatterns = [
    path('take-presence', TakePresenceEndPoint.as_view(), name='take-presence'),
    path('login', LoginEndPoint.as_view(), name='login'),
    path('logout', LogoutEndPoint.as_view(), name='logout'),
    path('auth-user', AuthenticatedUser.as_view(), name='auth-user'),
]

karisma/assistant/urls.py
from .views import *
from django.urls import path

app_name = 'assist'

urlpatterns = [
    path('', AssistantLanding.as_view(), name='landing'),
    path('create-class', CreateClass.as_view(), name='create-class'),
    path('join-class', JoinAssistantClas.as_view(), name='join-class'),
    path('change-username', AssistantChangeUsername.as_view(), name='change-username'),
    path('change-password', AssistantChangePassword.as_view(), name='change-password'),
    path('generate-token', GenerateTokenToResetPassword.as_view(), name='generate-token'),
    path('finder', FinderView.as_view(), name='finder'),
    path('download-today', DownloadTodayPresent.as_view(), name='today-present'),
    path('upload-boarding-hosue', CreateBoardingHouse.as_view(), name='create-boarding'),
    path('boarding-hosue-list', BoardingHouseList.as_view(), name='boarding-list'),

    path('my-class', MyClassList.as_view(), name='my-class-list'),
    path('my-class/<slug:link>/generate-qr', GenerateQRCodeView.as_view(), name='generate-qr'),
    path('my-class/<slug:link>/file/delete/<int:item_pk>', DeleteFile.as_view(), name='delete-file'),
    path('my-class/<slug:link>/file/<name>', QRCodeView.as_view(), name='view-qr'),
    path('my-class/<slug:link>/file', SeeAllFiles.as_view(), name='file-class'),
    path('my-class/<slug:link>/recaps/<qr_code>/export', recaps_csv, name='export'),
    path('my-class/<slug:link>/recaps/<qr_code>/absence', SetStudentAbsence.as_view(), name='absence'),
    path('my-class/<slug:link>/recaps/<qr_code>', PresenceRecap.as_view(), name='recaps'),
    path('my-class/<slug:link>/recaps', QRGeneratedList.as_view(), name='generated-qr'),
    path('my-class/<slug:link>/update-detail', update_class_detail, name='update-detail'),
    path('my-class/<slug:link>/score/update', UpdateScore.as_view(), name='update-score'),
    path('my-class/<slug:link>/score', AddStudentScore.as_view(), name='score'),
    path('my-class/<slug:link>/score/view', ViewStudentScore.as_view(), name='view-score'),
    path('my-class/<slug:link>/score/view/export', DownloadScore.as_view(), name='download-score'),
    path('my-class/<slug:link>/students', SeeAllStudents.as_view(), name='see-all-students'),
    path('my-class/<slug:link>', MyClass.as_view(), name='my-class'),
]

karisma/file_control/urls.py
from .views import *
from django.urls import path

app_name = 'file'

urlpatterns = [
    path('', UploadFile.as_view(), name='upload'),
    path('my-files', MyFiles.as_view(), name='all-file')
]

karisma/labs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
    path('static/<path>', serve, settings.STATIC_ROOT),
    path('media/<path>', serve, settings.MEDIA_ROOT),
]

urlpatterns += [
    path('file/', include('file_control.urls', namespace='file')),
    path('assistant/', include('assistant.urls', namespace='assist')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('presence.urls', namespace='presence')),
]

if not settings.DEBUG or settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

karisma/presence/urls.py
from .views import *
from django.urls import path

app_name = 'presence'


urlpatterns = [
    path('join-class', JoinClass.as_view(), name='join-class'),
    path('data-completions', DataComplement.as_view(), name='complete-data'),
    path('reset-password/request', RequestPasswordReset.as_view(), name='request-password-reset'),
    path('reset-password/<token>', ResetPassword.as_view(), name='reset-password'),
    path('presence', Presence.as_view(), name='take-presence'),
    path('class', ClassList.as_view(), name='class-list'),
    path('class/<slug:link>/upload-file', UploadFileByClass.as_view(), name='upload-file'),
    path('class/<slug:link>/file-list', FileListClass.as_view(), name='file-list-class'),
    path('class/<slug:link>/recaps', MyPresenceRecaps.as_view(), name='my-presence-recap'),
    path('class/<slug:link>/recaps/score', SeeMyScoreView.as_view(), name='my-score-recap'),
    path('dashboard', LandingView.as_view(), name='landing'),

    path('about', about_us, name='about'),
    path('merch', merchandise, name='merchandise'),
    path('faq', faq, name='faq'),

    path('', landing, name='landing-no-login'),
]

karisma/presence/forms.py
from django import forms
from django.apps import apps

from .models import *

Files = apps.get_model('file_control', 'Files')
TokenToResetPassword = apps.get_model('assistant', 'TokenToResetPassword')
StudentScore = apps.get_model('assistant', 'StudentScore')
classification = ['PRETEST', 'LAPORAN', 'POST-TEST', 'UTS', 'UAS', 'All']
ResetPasswordRequest = apps.get_model('assistant', 'ResetPasswordRequest')


class UserCompletionForms(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class UserDataCompleteForms(forms.ModelForm):
    class Meta:
        model = UserData
        fields = ['nim', 'phone_number']


class UploadFileForms(forms.ModelForm):
    class Meta:
        model = Files
        fields = ['file']


class RequestPasswordResetForm(forms.ModelForm):
    class Meta:
        model = ResetPasswordRequest
        fields = ('user', )

karisma/presence/views.py
from http import HTTPStatus

from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q as __
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import *

from .forms import *
from .utils import *


def templates(temp: str):
    return f'presence/{temp}.html'


def landing(request):
    return render(request, templates('main_landing'), {'path': '/'})


def about_us(request):
    return render(request, templates('about'), {'path': '/about'})


def merchandise(request):
    return render(request, templates('merch'), {'path': '/merch'})


def faq(request):
    return render(request, templates('faq'), {'path': '/faq'})


class LandingView(View):
    def get(self, *args, **kwargs):
        return render(self.request, templates('mhs_landing'))

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        get_user = self.request.user
        return super(LandingView, self).dispatch(request, *args, **kwargs)


class JoinClass(View):
    def get(self, *args, **kwargs):
        return render(self.request, templates('join_class'))

    def post(self, *args, **kwargs):
        code = self.request.POST['class_code']
        get_class = ClassName.objects.filter(unique_code=code)
        if not get_class:
            messages.error(self.request, 'Kode Pleton Tidak Ditemukan')
            return redirect('presence:join-class')
        get_class = get_class[0]
        user = get_object_or_404(User, pk=self.request.user.pk)
        """ checking join is creator or not """
        if user == get_class.creator:
            messages.info(self.request, "Kamu tidak bisa menjadi murid Pleton sekaligus penanggung jawab!")
            return redirect('presence:join-class')

        if get_class in user.stud.all():
            messages.info(self.request, f"Kamu sudah masuk kedalam Pleton '{get_class.name}'")
            return redirect('presence:join-class')

        get_class.students.add(self.request.user)
        get_class.save()

        messages.info(self.request, f"Kamu sudah berhasil masuk kedalam Pleton {get_class.name}")
        return redirect("presence:join-class")

    @method_decorator(login_required(login_url='/accounts/login/'))
    @method_decorator(user_passes_test(lambda u: (u.user if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        return super(JoinClass, self).dispatch(request, *args, **kwargs)


class DataComplement(View):
    form_class = UserCompletionForms
    e_form_class = UserDataCompleteForms
    model = UserData
    template_name = templates('forms')

    def get(self, *args, **kwargs):
        user = User.objects.get(pk=self.request.user.pk)
        data = self.model.objects.filter(user=self.request.user)
        context = {'user': user}
        if hasattr(self.request.user, 'user'):
            context['profile'] = data[0]

        return render(self.request, self.template_name, context=context)

    def post(self, *args, **kwargs):
        first_name = self.request.POST.get('f_name')
        last_name = self.request.POST.get('l_name')
        email = self.request.POST.get('email')
        nim = self.request.POST.get('nim')
        phone: str = self.request.POST.get('phone')

        get_data = self.model.objects.filter(user=self.request.user)
        nim_list = [x.nim for x in self.model.objects.all()]
        msg, check = check_nim(nim_list, nim)

        phone = phone[1:] if phone.startswith('0') else phone

        """ check nim first """
        if hasattr(self.request.user, 'user'):
            get_user = User.objects.get(pk=self.request.user.pk)
            if get_user.user.nim != nim:
                if check:
                    messages.warning(self.request, msg)
                    return redirect('presence:complete-data')

            instance = get_data[0]
            instance.nim = nim
            instance.phone_number = phone
            instance.save()
            messages.info(self.request, 'data nim dan nomor telepon telah disimpan!')

        else:
            if check:
                messages.warning(self.request, msg)
                return redirect('presence:complete-data')

            instance = UserData(
                user=self.request.user,
                nim=nim,
                phone_number=phone
            )
            instance.save()

        user = User.objects.get(pk=self.request.user.pk)
        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.save()

        messages.info(self.request, 'Profile anda berhasil di update')
        return redirect('presence:complete-data')

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(DataComplement, self).dispatch(request, *args, **kwargs)


class ClassList(ListView):
    model = ClassName
    context_object_name = 'classes'
    template_name = templates('class_list')

    def get_queryset(self):
        model = self.model
        return model.objects.filter(students=self.request.user)

    @method_decorator(login_required(login_url='/accounts/login/'))
    @method_decorator(user_passes_test(lambda u: (u.user if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        return super(ClassList, self).dispatch(request, *args, **kwargs)


class Presence(View):
    def get(self, *args, **kwargs):
        return render(self.request, templates('cam'))

    @method_decorator(login_required(login_url='/accounts/login/'))
    @method_decorator(user_passes_test(lambda u: (u.user if hasattr(u, 'user') else False), '/'))
    def dispatch(self, request, *args, **kwargs):
        return super(Presence, self).dispatch(request, *args, **kwargs)


class UploadFileByClass(CreateView):
    model = Files
    slug_url_kwarg = 'link'
    slug_field = 'link'
    form_class = UploadFileForms
    query_pk_and_slug = True
    template_name = templates('upload')

    def get_success_url(self):
        return reverse('presence:file-list-class', kwargs={'link': self.kwargs['link']})

    def form_valid(self, form):
        class_ = ClassName.objects.get(link=self.kwargs['link'])
        form.instance.user = self.request.user
        form.instance.class_name = class_
        return super(UploadFileByClass, self).form_valid(form)

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(UploadFileByClass, self).dispatch(request, *args, **kwargs)


class FileListClass(ListView):
    model = Files
    template_name = templates('file_list_class')
    context_object_name = 'files'

    def get_queryset(self):
        get_date = self.request.GET.get('date')
        model = self.model
        return model.objects.filter(class_name__link=self.kwargs['link']).filter(
            __(time_stamp__date=get_date)) if get_date else model.objects.filter(class_name__link=self.kwargs['link'])

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(FileListClass, self).dispatch(request, *args, **kwargs)


class MyPresenceRecaps(ListView):
    model = Recap
    template_name = templates('recaps')
    context_object_name = 'recaps'

    def get_queryset(self):
        model = self.model
        return model.objects.filter(user=self.request.user, qr__class_name__link=self.kwargs['link'])

    @method_decorator(login_required(login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(MyPresenceRecaps, self).dispatch(request, *args, **kwargs)


class ResetPassword(View):
    template_name = templates('reset')
    model = [UserData, TokenToResetPassword, ResetPasswordRequest]

    def get(self, *args, **kwargs):
        token = self.model[1].objects.get(token=self.kwargs['token'])
        now = timezone.now()
        if now > token.valid_until:
            return HttpResponse(status=HTTPStatus.NOT_ACCEPTABLE)

        return render(self.request, self.template_name)

    def post(self, *args, **kwargs):
        nim = self.request.POST.get('nim')
        pass1 = self.request.POST.get('password1')
        pass2 = self.request.POST.get('password2')
        token = get_object_or_404(self.model[1], token=kwargs['token'])

        get_nim = self.model[0].objects.filter(nim=nim)
        if not get_nim:
            messages.warning(self.request, f"NIM {nim} tidak terdata di sistem!")
            return redirect(reverse('presence:reset-password', kwargs={'token': self.kwargs['token']}))

        nim = get_nim[0]
        if pass1 != pass2:
            messages.warning(self.request, "password harus sama")
            return redirect(reverse('presence:reset-password', kwargs={'token': self.kwargs['token']}))

        passw = pass2
        user = User.objects.get(username=nim.user.username)
        user.set_password(passw)
        user.save()

        to_update = ResetPasswordRequest.objects.get(user=nim.user, is_done=False)
        to_update.token = token
        to_update.is_done = True
        to_update.save()

        messages.info(self.request, f"Password berhasil di ganti!")
        return redirect(settings.LOGIN_URL)

    def dispatch(self, request, *args, **kwargs):
        token = self.kwargs['token']
        if not token:
            raise Http404
        # find token
        token = self.model[1].objects.filter(token=token)
        if not token:
            raise Http404("token not found")
        return super(ResetPassword, self).dispatch(request, *args, **kwargs)


class SeeMyScoreView(ListView):

karisma/presence/templates/presence/cam.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load l10n %}
{% block head %}
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js"
        integrity="sha256-/H4YS+7aYb9kJ5OKhFYPUjSJdrtV6AeyJOtTkw6X72o=" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <script src="{% static 'user/js/html5-qrcode.min.js' %}"></script>
    <!--    <script src="{% static 'user/js/qrcode/minified/html5-qrcode.min.js' %}"></script>-->

    <div class="d-lg-flex">
        <div class="col-lg col mx-auto">
            <div class="card">
                <div class="card-body">
                    <div id="reader"></div>
                </div>
            </div>
        </div>
        <div class="col-lg col mx-auto">
            <h4>SCAN RESULT</h4>
            <div id="result"></div>
        </div>
    </div>
</div>

{% csrf_token %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script type="text/javascript">
    let token = document.getElementsByName("csrfmiddlewaretoken");
    console.log(token[0].value)
    let handle;

    function onScanSuccess(decodedText, decodedResult) {
        axios({
            method: 'post',
            url: '{% url "api:take-presence" %}?format=json',
            headers: {
                'X-CSRFToken': token[0].value,
                'Content-Type': 'application/json'
            },
            data: {
                "code": String(decodedText),
                "number": "{{ request.user.id }}"
            }
        })
            .then(response => {
                alert(response.data.text)
                window.location.replace('{% url "presence:landing" %}')
            })
            .catch(error => {
                onScanFailure(error.response.data.text)
                alert(handle)
                window.location.replace('{% url "presence:landing" %}')
            })
        // document.getElementById('result').innerHTML = '<span class="alert alert-info">' + handle + '</span>'
        // console.log(`Code matched = ${decodedText}`, decodedResult);
    }

    function onScanFailure(error) {
        handle = error;
    }

    let html5QrcodeScanner = new Html5QrcodeScanner(
        "reader",
        {fps: 10, qrbox: {width: 250, height: 250}},
        /* verbose= */ false);
    html5QrcodeScanner.render(onScanSuccess, onScanFailure);

</script>
{% endblock %}

karisma/presence/templates/presence/cam2.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load l10n %}
{% block title %} Read QR For Presence {% endblock %}

{% block head %}

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js" integrity="sha256-/H4YS+7aYb9kJ5OKhFYPUjSJdrtV6AeyJOtTkw6X72o=" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="d-lg-flex">
        <div class="col-lg-6">
            <div class="card" id="reader"></div>
        </div>
        <label for="result">QR Code Scan </label>
        <div class="col-lg-6"><input type="text" name="result" id="result" class="form-control" readonly></div>
    </div>
</div>

{% csrf_token %}
<script src="{% static 'user/js/html5-qrcode.min.js' %}"></script>
<script>
    let handle, token;
    token = document.getElementsByName("csrfmiddlewaretoken");
    console.log(token[0].value)

    function onScanSuccess(decodedText, decodedResult) {
        axios({
            method: 'post',
            url: '{% url "api:take-presence" %}?format=json',
            headers: {
                'X-CSRFToken': token[0].value,
                'Content-Type': 'Application/json'
            },
            data: {
                "code": String(decodedText),
                "number": "{{ request.user.id }}"
            }
        })
        .then(response => {
            console.log(response)
            window.location.replace('{% url "presence:landing" %}')
        })
        .catch(error => {
            onScanError(error.response.data.text)

        })
        document.getElementById('result').value = handle;
        // document.getElementById('result').innerHTML = '<span class="alert alert-info">' + handle + '</span>'
        console.log(`Scan result: ${decodedText}`, decodedResult);
    }

    function onScanError(errorMessage) {
        handle = errorMessage
    }

    let html5QrcodeScanner = new Html5QrcodeScanner(
        "reader", {fps: 10, qrbox: 250});
    html5QrcodeScanner.render(onScanSuccess, onScanError);
</script>

{% endblock %}

karisma/presence/templates/presence/class_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <a href="{% url 'presence:join-class' %}" class="btn btn-primary">Join Pleton</a>
    <a href="{% url 'presence:landing' %}" class="btn btn-secondary">Back To Home</a>
    <div class="table-responsive my-3">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nama Kelas</th>
                <th scope="col">PJ Cofass</th>
                <th scope="col">Mentorship Pleton</th>
                <th scope="col">Recaps</th>
            </tr>
            </thead>
            <tbody>
            {% for class in classes %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ class }}</td>
                <td>{{ class.creator }}</td>
                <td>
                    {% for pr in class.pr.all %}
                    {{ pr }} <br>
                    {% endfor %}
                </td>
                <td>
                    <a href="{% url 'presence:my-presence-recap' class.link %}" class="btn btn-primary mt-0 mx-1 mb-1">Presence Recaps</a>
                </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

karisma/presence/templates/presence/file_list_class.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <div class="row mx-auto">
        <div class="col-5">
            <h2>My FIle in {{ class }}</h2>
        </div>
        <form method="get" class="col-7">
            <div class="row mx-auto">
                <input type="date" name="date" id="date" class="form-control col-10">
                <div class="form-group col-2">
                    <button class="btn btn-primary">set</button>
                </div>
            </div>
        </form>
    </div>

    <div class="table-responsive">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">FIle Owner</th>
                    <th scope="col">Item name</th>
                    <th scope="col">Upload date</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
            {% for file in files %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ file.user.first_name }} {{ file.user.last_name }}</td>
                    <td>{{ file.name }}</td>
                    <td>{{ file.date }}</td>
                    <td><a href="{% url 'assist:delete-file' view.kwargs.link file.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

karisma/presence/templates/presence/forms.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5 mx-auto">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% load crispy_forms_tags %}
        <div class="form-group">
            <label for="f_name">First Name</label>
            <input type="text" name="f_name" id="f_name" class="textinput textInput form-control" value="{{ user.first_name }}" required>
        </div>

        <div class="form-group">
            <label for="l_name">Last Name</label>
            <input type="text" name="l_name" id="l_name" class="textinput textInput form-control" value="{{ user.last_name }}" required>
        </div>

        <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" name="email" id="email" class="textinput textInput form-control" value="{{ user.email }}">
        </div>

        <div class="form-group">
            <label for="nim">NIM</label>
            <input type="text" name="nim" id="nim" class="textinput textInput form-control" value="{{ profile.nim }}" required>
        </div>

        <div class="form-group">
            <label for="phone">Phone Number</label>
            <input type="text" name="phone" id="phone" class="textinput textInput form-control" value="{{ profile.phone_number }}">
        </div>

        <div class="form-group">
            <button class="btn btn-primary">Save</button>
            <a href="{% url 'presence:join-class' %}" class="btn btn-secondary">Join Pleton</a>
            <a href="{% url 'presence:landing' %}" class="btn btn-secondary">Back To Home </a>
        </div>
    </form>
</div>
{% endblock %}

karisma/presence/templates/presence/join_class.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5 mx-auto">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="class_code">Kode Kelas</label>
            <input type="text" name="class_code" id="class_code" class="form-control">
        </div>
        <div class="form-group">
            <button class="btn btn-primary">Save</button>
            <a href="{% url 'presence:class-list' %}" class="btn btn-secondary">Pleton Saya</a>
            <a href="{% url 'presence:landing' %}" class="btn btn-secondary">Back To Home </a>
        </div>
    </form>
</div>
{% endblock %}

karisma/presence/templates/presence/mhs_landing.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid mt-5 mx-auto">
    <div class="row mx-auto align-items-center justify-content-center">

        <div class="col-lg-4 col-md-6 col-12">
            <div class="card p-4 mb-3">
                <div class="card-body">
                    <h5 class="card-title">Presensi</h5>
                    <p class="card-text">pindah ke halaman presensi</p>
                    <a href="{% url 'presence:take-presence' %}" class="btn btn-primary col">Presensi</a>
                </div>
            </div>

        </div>
        <div class="col-lg-4 col-md-6 col-12">
            <div class="card p-4 mb-3">
                <div class="card-body">
                    <h5 class="card-title">Data Pribadi</h5>
                    <p class="card-text">pindah ke halaman lengkapi data pribadi</p>
                    <a href="{% url 'presence:complete-data' %}" class="btn btn-primary col">Lengkapi Data</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 col-12">
            <div class="card p-4 mb-3">
                <div class="card-body">
                    <h5 class="card-title">Pleton</h5>
                    <p class="card-text">pindah ke halaman daftar Pleton</p>
                    <a href="{% url 'presence:class-list' %}" class="btn btn-primary col">Daftar Pleton</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 col-12">
            <div class="card p-4 mb-3">
                <div class="card-body">
                    <h5 class="card-title">Gabung Pleton</h5>
                    <p class="card-text">pindah ke halaman untuk masukan kode Pleton</p>
                    <a href="{% url 'presence:join-class' %}" class="btn btn-primary col">Gabung</a>
                </div>
            </div>
        </div>

        {% if user.user.is_controller %}
        <div class="col-lg-4 col-md-6 col-12">
            <div class="card p-4 mb-3">
                <div class="card-body">
                    <h5 class="card-title">Committee Page</h5>
                    <p class="card-text">pindah ke halaman Khusus Panitia</p>
                    <a href="{% url 'assist:landing' %}" class="btn btn-primary col">Committee</a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

karisma/presence/templates/presence/recaps.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <div class="table-responsive">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Code</th>
                <th scope="col">Generated</th>
                <th scope="col">Response</th>
            </tr>
            </thead>
            <tbody>
            {% for rec in recaps %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ rec.qr.qr_code }}</td>
                <td>{{ rec.qr.created }}</td>
                <td>{{ rec.time_stamp }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

karisma/presence/templates/presence/reset.html
{% extends 'base.html' %}

{% block title %} Reset Password {% endblock %}

{% block content %}
<div class="container my-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
          <div class="form-group">
              <label for="nim">NIM</label>
              <input type="text" class="form-control" id="nim" name='nim' aria-describedby="password1">
          </div>
          <div class="form-group">
              <label for="password1">Password</label>
              <input type="password" class="form-control" id="password1" aria-describedby="password1" name="password1">
          </div>
          <div class="form-group">
              <label for="password2">Re-Type Password</label>
              <input type="password" class="form-control" id="password2" name="password2">
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
    </form>
</div>
{% endblock %}

karisma/presence/templates/presence/upload.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <div class="card">
        <div class="card-body">
            {% load crispy_forms_tags %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="form-group">
                    <button class="btn btn-primary">Save</button>
                    <a href="{% url 'file:all-file' %}" class="btn btn-secondary">My Files</a>
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock %}